name: Publish Angular Lib to npm

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Temporary absolute minimal step to verify it works in UI
      - name: Verify
        run: echo "Workflow is visible!"
